/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rumahsakit;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Scanner;
import java.awt.*;
/**
 *
 * @author X230
 */
public class Layanan extends javax.swing.JFrame {
DefaultTableModel tabModel;
ResultSet RS=null;
    /**
     * Creates new form DataPasien
     */
    public Layanan() {
        initComponents();
        showData();
    }

        private void showData(){
        try{
            Object[] judul_kolom = {"id_layanan", "id_pasien", "id_dokter", "jenis", "keterangan", "waktu", "harga"};
            tabModel=new DefaultTableModel(null,judul_kolom);
            TabelPasien.setModel(tabModel);
            
            Connection conn=(Connection)koneksi.koneksiDB();
            Statement stt=conn.createStatement();
            tabModel.getDataVector().removeAllElements();
            
            RS=stt.executeQuery("SELECT * from layanan ");  
            while(RS.next()){
                Object[] data={
                    RS.getString("id_layanan"),
                    RS.getString("id_pasien"),
                    RS.getString("id_dokter"),
                    RS.getString("jenis"),
                    RS.getString("keterangan"),
                    RS.getString("waktu"),
                    RS.getString("harga")  
                };
               tabModel.addRow(data);
            }                
        } catch (Exception ex) {
        System.err.println(ex.getMessage());
        }
    }
   
    //show data to form when click data on table
    //menampilkan data ke form saat data pada tabel di klik
    void tableToForm(){
        jTextFieldIdL.setText(tabModel.getValueAt(TabelPasien.getSelectedRow(),0)+"");
        jTextFieldIdP.setText(tabModel.getValueAt(TabelPasien.getSelectedRow(),1)+"");
        jTextFieldIdD.setText(tabModel.getValueAt(TabelPasien.getSelectedRow(),2)+"");
        jComboBoxJenis.setSelectedItem(tabModel.getValueAt(TabelPasien.getSelectedRow(),3)+"");
        textAreaKet.setText(tabModel.getValueAt(TabelPasien.getSelectedRow(),4)+"");
        jTextFieldWaktu.setText(tabModel.getValueAt(TabelPasien.getSelectedRow(),5)+"");
        jTextFieldHarga.setText(tabModel.getValueAt(TabelPasien.getSelectedRow(),6)+"");
        
        buttonUpdate.setEnabled(true);
        buttonDelete.setEnabled(true);
        buttonSave.setEnabled(false);
    }
    
    //clear the form
    //membersihkan isian form 
    private void clearData(){
        
        jTextFieldHarga.setText("");
        jTextFieldIdP.setText(""); 
        jTextFieldIdD.setText("");
        jTextFieldWaktu.setText("");
        textAreaKet.setText("");
        jComboBoxJenis.setSelectedIndex(0);
        
    } 
    
    //disable to fill in form
    //tidak membolehkan untuk mengisi form
    private void SetEditOff(){
        jTextFieldHarga.setEnabled(false);
        jTextFieldIdP.setEnabled(false); 
        jTextFieldIdD.setEnabled(false);
        jTextFieldWaktu.setEnabled(false);
        textAreaKet.setEnabled(false);
        jComboBoxJenis.setEnabled(false);
    }
    
    //enable to fill in form
    //membolehkan untuk mengisi form
    private void seteditOn(){
        jTextFieldHarga.setEnabled(true);
        jTextFieldIdP.setEnabled(true); 
        jTextFieldIdD.setEnabled(true);
        jTextFieldWaktu.setEnabled(true);
        textAreaKet.setEnabled(true);
        jComboBoxJenis.setEnabled(true);
    }
 
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TabelPasien = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldIdP = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldIdD = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldWaktu = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldHarga = new javax.swing.JTextField();
        textAreaKet = new java.awt.TextArea();
        buttonNew = new java.awt.Button();
        buttonUpdate = new java.awt.Button();
        buttonDelete = new java.awt.Button();
        buttonSave = new java.awt.Button();
        jComboBoxJenis = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldIdL = new javax.swing.JTextField();
        button1 = new java.awt.Button();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Maju Jaya Medical");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TabelPasien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TabelPasien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelPasienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelPasien);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 104, 739, 510));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(1, 1, 1));
        jLabel1.setText("Layanan");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 12, -1, -1));

        jTextFieldIdP.setToolTipText("");
        jTextFieldIdP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIdPActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldIdP, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 161, -1));

        jLabel2.setForeground(new java.awt.Color(1, 1, 1));
        jLabel2.setText("ID Pasien");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, 30));

        jLabel3.setForeground(new java.awt.Color(1, 1, 1));
        jLabel3.setText("ID Dokter");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, 20));

        jTextFieldIdD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIdDActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldIdD, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 161, -1));

        jLabel5.setForeground(new java.awt.Color(1, 1, 1));
        jLabel5.setText("Keterangan");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, -1, 20));

        jLabel6.setForeground(new java.awt.Color(1, 1, 1));
        jLabel6.setText("Waktu");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 90, 20));

        jLabel7.setForeground(new java.awt.Color(1, 1, 1));
        jLabel7.setText("Harga");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 80, 20));

        jTextFieldWaktu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldWaktuActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldWaktu, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 161, -1));

        jLabel8.setForeground(new java.awt.Color(1, 1, 1));
        jLabel8.setText("Jenis ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 90, 20));

        jTextFieldHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHargaActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 161, -1));
        getContentPane().add(textAreaKet, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, 160, 80));

        buttonNew.setLabel("New");
        buttonNew.setName(""); // NOI18N
        buttonNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNewActionPerformed(evt);
            }
        });
        getContentPane().add(buttonNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, 50, -1));

        buttonUpdate.setLabel("Update");
        buttonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(buttonUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 500, 50, -1));

        buttonDelete.setLabel("Delete");
        buttonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(buttonDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 500, 50, -1));

        buttonSave.setLabel("Save");
        buttonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaveActionPerformed(evt);
            }
        });
        getContentPane().add(buttonSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 500, 50, -1));

        jComboBoxJenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Umum", "Khusus" }));
        jComboBoxJenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxJenisActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxJenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 161, -1));
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        jLabel4.setForeground(new java.awt.Color(1, 1, 1));
        jLabel4.setText("ID Layanan");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, 30));

        jTextFieldIdL.setToolTipText("");
        jTextFieldIdL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIdLActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldIdL, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 161, -1));

        button1.setLabel("Kembali");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        getContentPane().add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 560, 60, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rumahsakit/Logo-PBO-kecil-bgt.png"))); // NOI18N
        jLabel11.setText("Logo");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rumahsakit/Bg-PBO-coab.jpg"))); // NOI18N
        jLabel9.setText("background");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldIdPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIdPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIdPActionPerformed

    private void jTextFieldIdDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIdDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIdDActionPerformed

    private void jTextFieldHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldHargaActionPerformed

    //process for making new data
    //proses untuk membuat data data
    private void buttonNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNewActionPerformed
        // TODO add your handling code here:
        clearData();
        buttonSave.setEnabled(true);
        buttonUpdate.setEnabled(false);
        buttonDelete.setEnabled(false);
        seteditOn();
        jTextFieldIdL.setEnabled(false);
    }//GEN-LAST:event_buttonNewActionPerformed

    //process for updating data
    //proses untuk memperbaharui data
    private void buttonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUpdateActionPerformed
        // TODO add your handling code here:
        String id_p=jTextFieldIdP.getText();
        String jenis=jComboBoxJenis.getSelectedItem().toString();
        String harga=jTextFieldHarga.getText();
        String id_d=jTextFieldIdD.getText();
        String ket=textAreaKet.getText();        
        String id_layanan=textAreaKet.getText();
        
        java.util.Date tanggal = new java.util.Date();
        java.text.SimpleDateFormat TanggalFormat= new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        String waktu=TanggalFormat.format(tanggal);
        
        if (!(new Scanner(id_p).hasNextInt())) {
            JOptionPane.showMessageDialog(null,"ID Pasien harus angka");
            jTextFieldIdP.requestFocus();
        }else if (!(new Scanner(id_d).hasNextInt())) {
            JOptionPane.showMessageDialog(null,"ID Dokter harus angka");
            jTextFieldIdD.requestFocus();
        }else if (ket.isEmpty()) {
            JOptionPane.showMessageDialog(null,"Keterangan tidak boleh dikosongkan!");
            textAreaKet.requestFocus();
        }else if (!(new Scanner(harga).hasNextInt())) {
            JOptionPane.showMessageDialog(null,"Harga produk harus angka");
            jTextFieldHarga.requestFocus();
        }else{
            try{
                Connection conn=(Connection)koneksi.koneksiDB();
                Statement stt=conn.createStatement();
                stt.executeUpdate("UPDATE layanan SET id_pasien='"+id_p+"', id_dokter='"+id_d+"', jenis='"+jenis+"', keterangan='"+ket+"', waktu='"+waktu+"', harga='"+harga+"' WHERE id_layanan='"+id_layanan+"' ");
                clearData();
                showData();
                SetEditOff();
                JOptionPane.showMessageDialog(this,"Data berhasil disimpan","Success",JOptionPane.INFORMATION_MESSAGE);
            } catch(SQLException e){
                JOptionPane.showMessageDialog(this,"Simpan data gagal\n"+e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_buttonUpdateActionPerformed

    private void jComboBoxJenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxJenisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxJenisActionPerformed
   
    //process for saving data
    //proses untuk menyimpan data
    private void buttonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveActionPerformed
        // TODO add your handling code here:
        String id_p=jTextFieldIdP.getText();
        String jenis=jComboBoxJenis.getSelectedItem().toString();
        String harga=jTextFieldHarga.getText();
        String id_d=jTextFieldIdD.getText();
        String ket=textAreaKet.getText();        
        
        java.util.Date tanggal = new java.util.Date();
        java.text.SimpleDateFormat TanggalFormat= new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        String waktu=TanggalFormat.format(tanggal);
        
       if (!(new Scanner(id_p).hasNextInt())) {
            JOptionPane.showMessageDialog(null,"ID Pasien harus angka");
            jTextFieldIdP.requestFocus();
        }else if (!(new Scanner(id_d).hasNextInt())) {
            JOptionPane.showMessageDialog(null,"ID Dokter harus angka");
            jTextFieldIdD.requestFocus();
        }else if (ket.isEmpty()) {
            JOptionPane.showMessageDialog(null,"Keterangan tidak boleh dikosongkan!");
            textAreaKet.requestFocus();
        }else if (!(new Scanner(harga).hasNextInt())) {
            JOptionPane.showMessageDialog(null,"Harga produk harus angka");
            jTextFieldHarga.requestFocus();
        }else{
            try{
                Connection conn=(Connection)koneksi.koneksiDB();
                Statement stt=conn.createStatement();
                stt.executeUpdate("INSERT INTO layanan(id_pasien, id_dokter, jenis, keterangan, waktu, harga)"+
                    "VALUES('"+id_p+"','"+id_d+"','"+jenis+"','"+ket+"','"+waktu+"','"+harga+"')");
                clearData();
                showData();
                SetEditOff();
                JOptionPane.showMessageDialog(this,"Data berhasil disimpan","Success",JOptionPane.INFORMATION_MESSAGE);
            } catch(SQLException e){
                JOptionPane.showMessageDialog(this,"Simpan data gagal\n"+e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_buttonSaveActionPerformed

    //handling process when click data on pasien table
    //menangani proses saat tabel pasien di klik
    private void TabelPasienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelPasienMouseClicked
        // TODO add your handling code here:
        seteditOn();
        jTextFieldIdL.setEnabled(false);
        tableToForm();
    }//GEN-LAST:event_TabelPasienMouseClicked

    private void jTextFieldWaktuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldWaktuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldWaktuActionPerformed

    private void jTextFieldIdLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIdLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIdLActionPerformed

    //process for deleting data
    //proses untuk menghapus data
    private void buttonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteActionPerformed
        // TODO add your handling code here:
         String id_layanan=jTextFieldIdL.getText();

        if (id_layanan.isEmpty() ) {
            JOptionPane.showMessageDialog(null,"Id Layanan kosong");
            jTextFieldIdP.requestFocus();
        }else if(JOptionPane.showConfirmDialog(null,"Apakah anda yakin akan menghapus data ini?",
            "Informasi",JOptionPane.OK_CANCEL_OPTION,JOptionPane.INFORMATION_MESSAGE)==JOptionPane.OK_OPTION){
        try{
            Connection conn=(Connection)koneksi.koneksiDB();
            Statement stt=conn.createStatement();
            stt.executeUpdate("DELETE FROM layanan WHERE id_layanan='"+id_layanan+"'");
            clearData();
            showData();
            SetEditOff();
            JOptionPane.showMessageDialog(this,"Data berhasil di hapus","Success",JOptionPane.INFORMATION_MESSAGE);
        } catch(SQLException e){
            JOptionPane.showMessageDialog(this,"Delete data gagal\n"+e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        }
        }
    }//GEN-LAST:event_buttonDeleteActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new menuUtama().setVisible(true);
    }//GEN-LAST:event_button1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataPasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataPasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataPasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataPasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Layanan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabelPasien;
    private java.awt.Button button1;
    private java.awt.Button buttonDelete;
    private java.awt.Button buttonNew;
    private java.awt.Button buttonSave;
    private java.awt.Button buttonUpdate;
    private javax.swing.JComboBox<String> jComboBoxJenis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldHarga;
    private javax.swing.JTextField jTextFieldIdD;
    private javax.swing.JTextField jTextFieldIdL;
    private javax.swing.JTextField jTextFieldIdP;
    private javax.swing.JTextField jTextFieldWaktu;
    private java.awt.TextArea textAreaKet;
    // End of variables declaration//GEN-END:variables
}
